CREATE TABLE roles (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES ('admin'), ('editor'), ('viewer');

CREATE TABLE family_groups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL
);

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  family_group_id UUID REFERENCES family_groups(id) ON DELETE SET NULL,
  role_id INT NOT NULL DEFAULT 3 REFERENCES roles(id),
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE fridges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  creator_id UUID NOT NULL REFERENCES users(id),
  family_group_id UUID REFERENCES family_groups(id) ON DELETE SET NULL
);

CREATE TABLE foods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  quantity INT NOT NULL CHECK (quantity >= 0),
  fridge_id UUID NOT NULL REFERENCES fridges(id) ON DELETE CASCADE,
  expiration_date DATE
);

CREATE TABLE product_directory (
    foods_id SERIAL PRIMARY KEY,
    foods_name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE units (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  symbol TEXT NOT NULL UNIQUE,  -- сокращенное обозначение: шт, л, мл, г, кг
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  unit_id INT REFERENCES units(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE food_logs (
  id SERIAL PRIMARY KEY,
  action_type TEXT NOT NULL CHECK (action_type IN ('add', 'remove', 'move')),
  product_name TEXT NOT NULL,
  quantity DECIMAL(10, 2) NOT NULL,
  unit_symbol TEXT NOT NULL,
  from_fridge_id UUID REFERENCES fridges(id) ON DELETE SET NULL,
  to_fridge_id UUID REFERENCES fridges(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES users(id),
  user_name TEXT NOT NULL,
  fridge_name TEXT,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS journals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.need
(
    need_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000000 CACHE 1 ),
    foods_id integer NOT NULL,
    count integer NOT NULL,
    done boolean NOT NULL DEFAULT false,
    CONSTRAINT need_pkey PRIMARY KEY (need_id),
    CONSTRAINT need_foods_id_fkey FOREIGN KEY (foods_id)
        REFERENCES public.product_directory (foods_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
